// <auto-generated />
namespace Ef.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Recipe0301_Asynchronously : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recipe0301_Asynchronously));
        
        string IMigrationMetadata.Id
        {
            get { return "201711041327097_Recipe0301_Asynchronously"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
